"""Storage Protocol — the canonical interface every storage backend implements.

v1 ships only `FilesystemStorage`. Future SQLite or hybrid backends drop in here.
"""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from arctic_base.models import ObjectMeta, ResponseEvent, Theme, WorkbenchMeta


@runtime_checkable
class Storage(Protocol):
    # --- workbenches ---
    def list_workbenches(self) -> list[WorkbenchMeta]: ...
    def get_workbench(self, slug: str) -> WorkbenchMeta: ...
    def create_workbench(self, meta: WorkbenchMeta) -> WorkbenchMeta: ...
    def update_workbench(self, slug: str, patch: dict) -> WorkbenchMeta: ...
    def archive_workbench(self, slug: str) -> str: ...
    def restore_workbench(self, archive_name: str) -> str: ...
    def list_trash(self) -> list[str]: ...

    # --- theme ---
    def get_theme(self, slug: str) -> Theme: ...
    def get_theme_raw(self, slug: str) -> str: ...
    def put_theme(self, slug: str, raw_md: str) -> Theme: ...
    def list_theme_assets(self, slug: str) -> list[str]: ...
    def get_theme_asset(self, slug: str, path: str) -> tuple[bytes, str]: ...
    def put_theme_asset(self, slug: str, path: str, data: bytes) -> None: ...
    def delete_theme_asset(self, slug: str, path: str) -> None: ...

    # --- objects ---
    def list_objects(
        self, slug: str, *, kind: str | None = None, drawer: str | None = None
    ) -> list[ObjectMeta]: ...
    def get_object(self, slug: str, object_id: str) -> ObjectMeta: ...
    def create_object(
        self, slug: str, meta: ObjectMeta, content: bytes | None = None
    ) -> ObjectMeta: ...
    def update_object_meta(self, slug: str, object_id: str, patch: dict) -> ObjectMeta: ...
    def delete_object(self, slug: str, object_id: str) -> None: ...
    def get_object_content(self, slug: str, object_id: str) -> tuple[bytes, str]: ...
    def put_object_content(
        self, slug: str, object_id: str, data: bytes, if_match: str | None = None
    ) -> tuple[ObjectMeta, str]: ...

    # --- responses ---
    def list_responses(
        self, slug: str, object_id: str, since_version: int = 0
    ) -> list[ResponseEvent]: ...
    def get_latest_response(self, slug: str, object_id: str) -> ResponseEvent | None: ...
    def append_response(self, slug: str, object_id: str, event: ResponseEvent) -> ResponseEvent: ...
